### ISSUE TITLE
Issue running the app

### ISSUE THREAD

**Issue by ryananthonydrake** [jefferyleo/f.lux#14]
I keep getting this error:

![screen shot 2015-11-23 at 8 56 50 pm](https://cloud.githubusercontent.com/assets/3394807/11335042/c93da4de-9224-11e5-9bd9-0de1bc5adf29.png)

**Comment by silvercomet** [comment]
So you need to do what it said, just change the justgetflux to somerthing else or add your name after that identifier, iflux.yournamehere for example to make it different

**Comment by jefferyleo** [comment]
please change the identifier to another string, example, com.justgetflux.xxxx
