### ISSUE TITLE
Issue with iPad Pro

### ISSUE THREAD

**Issue by SpencerC** [jefferyleo/f.lux#16]
The app stops on the splash screen and the console prints the following over and over:
`2015-12-19 16:13:07.859 iflux[4534:163243] Waiting for display to come online...`

**Comment by adayguerra** [comment]
I got similar problem with an iPad Mini 2, after the splash the screen goes white and remains like that...

**Comment by damathews** [comment]
Same problem. Any iPad simulation causes an error where the splash screen goes through and then goes all white.

**Comment by cisolarix** [comment]
Same issue occurred to me. iPad mini 4 stopping on the splash screen and nothing more.

**Comment by 2ec** [comment]
Same problem for my iPhone 5 and 5s also. On my iPhone 5 I managed to successfully install after many attempts. I don't know what went right.
