### ISSUE TITLE
Crashing on iOS 9.2 13C75

### ISSUE THREAD

**Issue by fulldecent** [jefferyleo/f.lux#17]
This is crashing on iOS 9.2 13C75 for me. Not jailbroken.

When opening, the app does not get to the main screen, it just crashes.

Is anyone else experiencing this?

**Comment by kdrag0n** [comment]
I am also using iOS 9.2 non-jailbroken. When I open the app, it starts and just works like normal. Did you do something wrong during the build process? (any errors, etc?)

**Comment by fulldecent** [comment]
Build was error free. And it worked fine on 9.1. Broke on upgrade.

**Comment by kdrag0n** [comment]
Try rebuilding. There may be problems with the SDK changes (9.1 to 9.2), or an update may have affected the app in some way. Another problem there may be symbols.

**Comment by fulldecent** [comment]
Rebuilding fixed this issue, no idea why. Thanks for the advice. Closing.
