### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by abunchoftrees** [jefferyleo/f.lux#19]
After building the app and verifying myself as a developer on my phone, once I open the app all I get is a black screen. I'm running an iPhone 6s w/ iOS 9.2

**Comment by nneonneo** [comment]
I ran into this too. I found that redeploying the app via Xcode fixed the issue.

**Comment by ghost** [comment]
Same issue; have tried redeploying via Xcode and same error reoccurs.

**Comment by jefferyleo** [comment]
Sorry guys, f.lux has no tested with iOS 9.2, I think it only supported until 9.1 since there're much issues in iOS 9.2

**Comment by Mv826** [comment]
I have an iPhone 6s and an iPad Air 2 both running iOS 9.2 and f.lux just fine

**Comment by Joshfindit** [comment]
Installed here iPad Air 2, iOS 9.2, and no black screen issues.
