### ISSUE TITLE
Turning on & off in just a few seconds

### ISSUE THREAD

**Issue by iCoolchar** [jefferyleo/f.lux#25]
encounter a problem and a post in the f.lux forum also mentioned.

> I made the update to 37.1 version and since then, the app turn on and off and on every seconds ! It is very annoying, I feel like I'm in a fucking night club !!!
> Hopefully, I'm not epileptic !!!!!
> Does anyone have the same problem ???
> Because it didn't do this before, so I delete it & I download the 37.2 version, and it is the same !
> I like the app, but why doing new version if it's getting worst ???

Turning off auto brightness in the mac settings solved it. But I don't think it's a good solution. Hope the problem to be resolved as soon as possible. Thanks!

**Comment by 153957** [comment]
This repository is about the iOS app, not the Mac desktop application. This issue is in the wrong place.

**Comment by iCoolchar** [comment]
oh...sorry, closed.
