### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by fulldecent** [jefferyleo/f.lux#4]
Please create a release so the source can be downloaded as a ZIP

**Comment by designorant** [comment]
It would be good to create a release before the PR so tha SHA-1 matches (taking there were no alternations as I haven't tested it): https://justgetflux.com/forum/topic/1267/sha-1-for-ios-sideload

**Comment by timdmackey** [comment]
+1 for creating a release that matches the posted SHA-1 checksum

**Comment by wesselj1** [comment]
+2. Would be nice to be able to verify this project matches the checksum provided by Flux themselves for security.

**EDIT**: On the F.lux forums a user posted this virustotal link:
https://www.virustotal.com/en/file/38f463ee5780a4f2b0160f9fa21dbe3c78c5d80d3c093e4ff553aaca230e2898/analysis/#additional-info
which contains the main .zip sha256 checksum along with individual sha256 hashes for each individual file. I have at the least verified that the sha256 of the iflux binary matches. Herf of the F.lux team verified that the virus total link was correct.

Here is a link to the initial forum post:
https://justgetflux.com/forum/topic/1267/sha-1-for-ios-sideload

**Comment by jefferyleo** [comment]
Added! Sorry for the late
